### ISSUE TITLE
Add a .env.example file to both the frontend and the backend

### ISSUE THREAD

**Issue by WinterCore** [ELIASyASSER/book-store#1]
A `.env.example` file helps other developers who are trying to run your project on their machines to set it up quickly without having to go through the code and look for all the environment variables you've used.
eg:
```
CLIENT_URL=http://localhost:5173
MONGO_URI=mongodb://localhost:27017/book-store
JWT_SECRET=
CLOUD_NAME=
API_KEY=
API_SECRET=
```
Another note: You should prefix environment variables related to a specific external API service with the service name, so for example `API_KEY`, `API_SECRET` and `CLOUD_NAME` should be `CLOUDINARY_API_KEY`, `CLOUDINARY_API_SECRET` and `CLOUDINARY_CLOUD_NAME` respectively. Because `API_KEY` could mean anything unless you go through the code and try to figure out what API call is using it.

**Comment by ELIASyASSER** [comment]
awsome
