### ISSUE TITLE
You can't add books without a discount

### ISSUE THREAD

**Issue by WinterCore** [ELIASyASSER/book-store#6]
When adding a book, you have to fill both **Old Price** and **New Price**.

If I fill both inputs with the same price then this gets shown
<img width="589" alt="image" src="https://github.com/user-attachments/assets/61c80d3e-ed84-4290-b6c5-0854c1a26199">
<br />

There should be an "offer" checkbox maybe that switches between two states.
- On: Show **Old Price** and **New Price** inputs
- Off: Show a single **Price** input

**Comment by ELIASyASSER** [comment]
done pro
